//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ksiegarnia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresy
    {
        public Adresy()
        {
            this.Uzytkownicy = new HashSet<Uzytkownicy>();
        }
    
        public int id_adres { get; set; }
        public string ulica { get; set; }
        public string miasto { get; set; }
        public int nr_domu { get; set; }
        public int nr_mieszkania { get; set; }
        public string wojewodztwo { get; set; }
        public string kod_pocztowy { get; set; }
    
        public virtual ICollection<Uzytkownicy> Uzytkownicy { get; set; }
    }
}
