//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ksiegarnia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aktywacja
    {
        public int id { get; set; }
        public System.Guid kod { get; set; }
    
        public virtual Uzytkownicy Uzytkownicy { get; set; }
    }
}
