//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ksiegarnia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autorzy
    {
        public Autorzy()
        {
            this.AutorzyToKsiazki = new HashSet<AutorzyToKsiazki>();
            this.Ksiazki = new HashSet<Ksiazki>();
        }
    
        public int id_autora { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public int id_ksiazka { get; set; }
    
        public virtual ICollection<AutorzyToKsiazki> AutorzyToKsiazki { get; set; }
        public virtual ICollection<Ksiazki> Ksiazki { get; set; }
        public virtual Ksiazki Ksiazki1 { get; set; }
    }
}
