//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ksiegarnia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dzialy
    {
        public Dzialy()
        {
            this.Ksiazki = new HashSet<Ksiazki>();
        }
    
        public int id_dzial { get; set; }
        public string nazwa_dzialu { get; set; }
    
        public virtual ICollection<Ksiazki> Ksiazki { get; set; }
    }
}
