//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ksiegarnia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Egzemplarze
    {
        [Key]
        public int id_egzemplarz { get; set; }
        public Nullable<int> id_ksiazka { get; set; }

        [Display(Name = "Kod ean")]
        public string kod_ean { get; set; }
        [Display(Name = "Isbn")]
        public string isbn { get; set; }
        [Display(Name = "Iloœæ egzemplarzy")]
        public Nullable<int> stan { get; set; }
    
        public virtual Ksiazki Ksiazki { get; set; }
    }
}
