//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ksiegarnia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ksiazki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ksiazki()
        {
            this.AutorzyKsiazki = new HashSet<AutorzyKsiazki>();
            this.Egzemplarze = new HashSet<Egzemplarze>();
            this.Zamowienia_ksiazki = new HashSet<Zamowienia_ksiazki>();
        }
    
        public int id_ksiazka { get; set; }
        public Nullable<int> id_wydawnictwa { get; set; }
        public Nullable<int> id_kategoria { get; set; }
        public string tytul { get; set; }
        public string foto { get; set; }
        public double cena_netto_aktualna { get; set; }
        public double cena_brutto_aktualna { get; set; }
        public double proc_vat_aktualny { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorzyKsiazki> AutorzyKsiazki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Egzemplarze> Egzemplarze { get; set; }
        public virtual Kategoria Kategoria { get; set; }
        public virtual Wydawnictwa Wydawnictwa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienia_ksiazki> Zamowienia_ksiazki { get; set; }
    }
}
