//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ksiegarnia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ksiazki
    {
        public Ksiazki()
        {
            this.Autorzy1 = new HashSet<Autorzy>();
            this.AutorzyToKsiazki = new HashSet<AutorzyToKsiazki>();
        }
    
        public int id_ksiazka { get; set; }
        public string nazwa { get; set; }
        public int id_autor { get; set; }
        public string isbn { get; set; }
        public int cena { get; set; }
        public int id_dzial { get; set; }
        public string zdjecie { get; set; }
    
        public virtual Autorzy Autorzy { get; set; }
        public virtual ICollection<Autorzy> Autorzy1 { get; set; }
        public virtual Dzialy Dzialy { get; set; }
        public virtual ICollection<AutorzyToKsiazki> AutorzyToKsiazki { get; set; }
    }
}
