//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ksiegarnia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KsiegarniaEntities1 : DbContext
    {
        public KsiegarniaEntities1()
            : base("name=KsiegarniaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autorzy> Autorzy { get; set; }
        public virtual DbSet<AutorzyKsiazki> AutorzyKsiazki { get; set; }
        public virtual DbSet<Egzemplarze> Egzemplarze { get; set; }
        public virtual DbSet<Kategoria> Kategoria { get; set; }
        public virtual DbSet<Klienci> Klienci { get; set; }
        public virtual DbSet<Ksiazki> Ksiazki { get; set; }
        public virtual DbSet<Statusy> Statusy { get; set; }
      
        public virtual DbSet<Wydawnictwa> Wydawnictwa { get; set; }
        public virtual DbSet<Wysylki_platnosci> Wysylki_platnosci { get; set; }
        public virtual DbSet<Zamowienia> Zamowienia { get; set; }
        public virtual DbSet<Zamowienia_ksiazki> Zamowienia_ksiazki { get; set; }
        public virtual DbSet<Aktywacja> Aktywacja { get; set; }
    }
}
