//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ksiegarnia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzytkownicy
    {
        public int id_user { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public int wiek { get; set; }
        public string email { get; set; }
        public int id_adres { get; set; }
        public string haslo { get; set; }
        public string nr_telefonu { get; set; }
    
        public virtual Adresy Adresy { get; set; }
    }
}
