//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ksiegarnia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzytkownicy
    {
        public int id_user { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public int wiek { get; set; }
        public string email { get; set; }
        public string haslo { get; set; }
        public string nr_telefonu { get; set; }
        public int aktywny { get; set; }
        public string ulica { get; set; }
        public string miasto { get; set; }
        public Nullable<int> nr_domu { get; set; }
        public Nullable<int> nr_mieszkania { get; set; }
        public string wojewodztwo { get; set; }
        public string kod_pocztowy { get; set; }
        public string haslo_potw { get; set; }
    
        public virtual Aktywacja Aktywacja { get; set; }
    }
}
