//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ksiegarnia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Uzytkownicy
    {
        public int id_user { get; set; }
        [Required]
        [Display(Name="Imie")]
        public string imie { get; set; }
        [Required]
        [Display(Name = "Nazwisko")]
        public string nazwisko { get; set; }
        [Required]
        [Display(Name = "Wiek")]
        public int wiek { get; set; }
        [Required]
        [Display(Name = "E-mail")]
        public string email { get; set; }
        public int id_adres { get; set; }
        [Required]
        [Display(Name = "Hasło")]
        [DataType(DataType.Password)]
        public string haslo { get; set; }
        [Required]
        [Display(Name = "Nr telefonu")]
        public string nr_telefonu { get; set; }
        public int aktywny { get; set; }
    
        public virtual Adresy Adresy { get; set; }
        public virtual Aktywacja Aktywacja { get; set; }
    }
}
