//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ksiegarnia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowienia_ksiazki
    {
        public int id_zamowienia_ksiazki { get; set; }
        public Nullable<int> id_ksiazki { get; set; }
        public Nullable<int> id_zamowienia { get; set; }
        public Nullable<double> proc_vat_zakupu { get; set; }
        public Nullable<double> cena_brutto_zakupu { get; set; }
        public Nullable<double> cena_netto_zakupu { get; set; }
        public Nullable<int> ilosc_ksiazek { get; set; }
        public string tytul { get; set; }
    
        public virtual Ksiazki Ksiazki { get; set; }
        public virtual Zamowienia Zamowienia { get; set; }
    }
}
