//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ksiegarnia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowienia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zamowienia()
        {
            this.Zamowienia_ksiazki = new HashSet<Zamowienia_ksiazki>();
        }
    
        public int id_zamowienia { get; set; }
        public Nullable<int> id_klient { get; set; }
        public Nullable<int> id_wysylka { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<double> suma { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string wysylka_nazwa { get; set; }
        public Nullable<int> wysylka_cena { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual Statusy Statusy { get; set; }
        public virtual Wysylki_platnosci Wysylki_platnosci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienia_ksiazki> Zamowienia_ksiazki { get; set; }
    }
}
