//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ksiegarnia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowienia
    {
        public int id_zamowienia { get; set; }
        public int id_user { get; set; }
        public Nullable<System.DateTime> data_zlozenia_zam { get; set; }
        public int cena_calkowita { get; set; }
    }
}
